name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  api:
    name: Integrate api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # TODO cache the following step if it gets too slow
      - name: Install dependencies
        run: npm install
      - name: Check linting
        run: npm run lint
      - name: Compile project
        run: npm run build
      - name: Run tests
        run: npm run test

  www:
    name: Integrate www
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./www
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: TODO add more steps
        run: echo 'Hello World!'
