name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  api:
    name: Integrate api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Compile project
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Check formatting
        run: npm run format:check
      - name: Check linting
        run: npm run lint
